# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-pinkraspi"
BBFILE_PATTERN_meta-pinkraspi = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-pinkraspi = "6"

LAYERDEPENDS_meta-pinkraspi = "core"
LAYERSERIES_COMPAT_meta-pinkraspi = "scarthgap walnascar"

DISTRO_FEATURES:append = " systemd pam usrmerge polkit"

LICENSE_FLAGS_ACCEPTED = "commercial"
